### PR TITLE
Master

### PR DESCRIPTION
**Pull request by sirduke**
Remove unused breaking reference

### CODE REVIEW

**Comment by hmemcpy** [comment]
Seriously????

**Comment by SirDuke** [comment]
At least, works for me :-)

**Comment by hmemcpy** [comment]
This what caused the usages issue?

**Comment by SirDuke** [comment]
Looks like, this caused exception from the plugin, and that exception
caused failure in ReSharper's usage analyzer.
 I'm also going to fix ReSharper's usage analyzer to be more tolerant to
exceptions from plugins.

**Comment by hmemcpy** [comment]
Well, thank you so much for fixing it!
I'll upload a new version!

**Pull request merged**
